---
- name: "Deploy a Web Server"
  hosts: all
  become: true
#  handlers:
#    - name: debug
#      debug:
#        msg: "MariaDB has been installed so that MySQL installation failed."
  tasks:
    - name: "Update system packages"
      dnf:                                  # module
        name: "*"                           # argument
        state: latest                       # argument
        exclude: kernel*                    # argument
      when: ansible_os_family == 'CentOS'   # condition
            
    - name: "Block and rescue task"
      block:
        - name: "Install required packages"
          dnf:
            name: "{{ item }}"
            state: present
          register: dnf_results
          loop:                                 # the loop scope is inside of the task
            - httpd
            - php
            - mysql
#          notify: debug
      rescue:
        - name: output register - dns_results
          debug:
            msg: "{{ dnf_results }}"
          ignore_errors: true
        - name: Fail if return code is not 0
          fail:
            msg: "The package ({{ item.name }}) failed to install."
          when: item.rc != 0
          loop: "{{ dnf_results.results }}"
