---
- name: "Deploy a Web Server"
  hosts: all
  become: true
#  handlers:
#    - name: debug
#      debug:
#        msg: "MariaDB has been installed so that MySQL installation failed."
  tasks:
    - name: "Update system packages"
      dnf:                                  # module
        name: "*"                           # argument
        state: latest                       # argument
        exclude: kernel*                    # argument
      when: ansible_os_family == 'CentOS'   # condition
            
    - name: "Block and rescue task"
      block:
        - name: "Install required packages"
          dnf:
            name: "{{ item }}"
            state: present
          register: results
          loop:                                 # the loop scope is inside of the task
            - httpd
            - php
            - mysql
#          notify: debug
      rescue:
        - name: stdout
          debug:
            msg: "{{ results }}"
          ignore_errors: true
        - name: stderr
          debug:
            msg: "{{ results.stderr_lines }}"
          ignore_errors: true
        - name: debug output
          debug:
            msg: "MariaDB has been installed so that MySQL installation failed."
#          when: "'mariadb' in ansible_failed_result"
