---
- name: "Deploy a Web Server"
  hosts: all
  become: true
#  handlers:
#    - name: debug
#      debug:
#        msg: "MariaDB has been installed so that MySQL installation failed."
  tasks:
    - name: "Update system packages"
      dnf:                                  # module
        name: "*"                           # argument
        state: latest                       # argument
        exclude: kernel*                    # argument
      when: ansible_os_family == 'CentOS'   # condition
            
    - name: "Install required packages"
      block:
        dnf:
          name: "{{ item }}"
          state: present
        loop:                                 # the loop scope is inside of the task
          - httpd
          - php
          - mysql
        register: result 
#      notify: debug
      rescue:
        - name: debug output
          debug:
            msg: "MariaDB has been installed so that MySQL installation failed."
          when: "result.msg contains mariadb"
